name: Rebase from upstream every 15 days
on:
  schedule:
    - cron:  '0 0 */7 * *' # New cron job for rebasing every 7 days
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Rebase from upstream
        run: |
          git remote add upstream https://github.com/BennyThadikaran/eod2
          git fetch upstream
          git rebase upstream/main
      - name: Push changes
        run: |
          git config --global user.name "shikharvaish28"
          git config --global user.email "shikarvaish@gmail.com"
          git push origin main
